# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Content/data.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x43ontent/data.proto\x12\raccelerometer\"3\n\x10RawDataTypeValue\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\t\n\x01z\x18\x03 \x01(\x05\"B\n\x15\x44\x61taBusRequestContent\x12)\n\x08\x64\x61taType\x18\x01 \x01(\x0e\x32\x17.accelerometer.DataType\"\xb0\x01\n\x16\x44\x61taBusResponseContent\x12\x10\n\x08\x64\x65viceId\x18\x01 \x01(\r\x12)\n\x08\x64\x61taType\x18\x02 \x01(\x0e\x32\x17.accelerometer.DataType\x12\r\n\x05nonce\x18\x03 \x01(\x05\x12\x11\n\tsuspended\x18\x04 \x01(\x05\x12.\n\x03raw\x18\x05 \x01(\x0b\x32\x1f.accelerometer.RawDataTypeValueH\x00\x42\x07\n\x05value*!\n\x08\x44\x61taType\x12\x0c\n\x08\x44\x61taNone\x10\x00\x12\x07\n\x03Raw\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Content.data_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DATATYPE']._serialized_start=337
  _globals['_DATATYPE']._serialized_end=370
  _globals['_RAWDATATYPEVALUE']._serialized_start=37
  _globals['_RAWDATATYPEVALUE']._serialized_end=88
  _globals['_DATABUSREQUESTCONTENT']._serialized_start=90
  _globals['_DATABUSREQUESTCONTENT']._serialized_end=156
  _globals['_DATABUSRESPONSECONTENT']._serialized_start=159
  _globals['_DATABUSRESPONSECONTENT']._serialized_end=335
# @@protoc_insertion_point(module_scope)
